apiVersion: v2
name: caddy
description: Caddy web server Helm chart for Kubernetes
type: application
version: 1.0.0
appVersion: "2.8.0"
keywords:
  - caddy
  - web-server
maintainers:
  - name: Xurshid
    email: your.email@example.com
